Admin receives a commission on claimed payment
holdex/payment-streaming pull request #14
Opened 2023-06-29 15:58 UTC by accompany1205

Resolve #6

2023-06-29 15:59 UTC, accompany1205 commented
@markholdex , @georgeciubotaru Could you review this PR?

2023-06-29 16:00 UTC, accompany1205 commented
@markholdex , @georgeciubotaru Could you review this PR?

2023-06-30 06:00 UTC, zolotokrylin requested changes

2023-06-30 09:26 UTC, markholdex approved these changes

2023-06-30 09:27 UTC, merged