Problem: "accumulation()" function has no test cases #50
holdex/payment-streaming pull request #54
Opened 2023-07-07 09:39 UTC by CTAPCKPIM

2023-07-07 09:44 UTC, CTAPCKPIM commented
@accompany1205 
Help pls

 - TODO: 
**Solve the problem with the fact that the numbers do not converge**
_I have been thinking and trying different options for more than an hour, and without results_

**Adding other tests for this function**
_I'll do it myself but stalled over the above_

2023-07-07 09:52 UTC, CTAPCKPIM commented
I think the problem is in lines **186, 187**
Like something at the stage when we rewind time
![image](https://github.com/holdex/payment-streaming/assets/83241890/b52fa153-6fca-445e-aaa9-9651d6f8b858)

2023-07-07 11:19 UTC, CTAPCKPIM commented
- Done, `accumulation();` has tests

2023-07-08 10:52 UTC, zolotokrylin commented
sync with main branch 
tnx

2023-07-11 06:41 UTC, zolotokrylin requested changes
sync the branch (resolve conflicts)

2023-07-11 08:56 UTC, markholdex commented
Accumulation function already has tests. Closing this PR

2023-07-11 08:56 UTC, closed without merging

2023-07-11 08:56 UTC, markholdex commented on test/StreamManager.test.js
> +    const expectedAmount = Math.floor(this.cliffPeriod * this.amount / 30 / 24 / 3600)
Not correctly calculated. During cliff period, 0 amount is accumulated. Check existing tests