Problem: "claim" function has no test cases #47
holdex/payment-streaming pull request #57
Opened 2023-07-07 21:41 UTC by CTAPCKPIM

TODO:
   1) fix: Claim: if reentrant call is detected;
   2) fix: Claim: insufficient balance // working when .only
   2) writing the test for `else` in `claim();`
   3) writing the test for `revert CanNotClaimAnyMore();`
   4) writing the test for `nonReentrant` (modifier)

2023-07-08 10:40 UTC, zolotokrylin requested changes

2023-07-08 10:40 UTC, zolotokrylin commented on test/StreamManager.test.js
> +  // Returning 0, because the current timestamp is less than the sum of the thread creation time and the "cliff" period
```suggestion
  // Returning 0, because the current timestamp is less than the sum of the stream creation time and the "cliff" period 
```

2023-07-08 10:49 UTC, zolotokrylin commented
Please resolve the conflicts (merge main into this branch)

2023-07-11 09:15 UTC, markholdex commented
@CTAPCKPIM  If you check the code, we already have tests on claim function. Plus in this PR, we introduce a lot of changes to other functions like accumulation. Not good. Maybe if the conflicts will be resolved in favor of existing code, it will be fine. But for now, I can't accept these changes.

2023-07-11 12:25 UTC, CTAPCKPIM commented
@zolotokrylin / @markholdex 
In principle, the tests are written, this is what the "coverage" shows
![image](https://github.com/holdex/payment-streaming/assets/83241890/555a6824-73ac-4f79-ac4c-7ad1c1a9d249)

What is left, but I didn’t test it, I can’t write a test that hooks "_nonReentrantBefore()" in the contract "ReentrancyGuard"
![image](https://github.com/holdex/payment-streaming/assets/83241890/43daa6cd-dd4d-43a9-9b02-a9717bfde434)

2023-07-11 16:44 UTC, CTAPCKPIM commented
That is, you need to write different versions of the plots with tests to check the functions of the contract?

Will you close this **PR** since the tests were written before me?

It's just that if I'm not mistaken, then there are tests that are not on the **'main'** branch, if I'm still wrong, then correct me

2023-07-12 12:02 UTC, markholdex commented
@CTAPCKPIM your branch is out of date compared to the main. Please update the branch first. 
<img width="713" alt="image" src="https://github.com/holdex/payment-streaming/assets/46079535/8c3cadd9-7be6-4d3a-a0ac-c3164b09e2e2">


Then we will see what are the differences in this PR. 

---

Also fix English typo everywhere you have. Because `Expecing rever` is not clear. 

<img width="353" alt="image" src="https://github.com/holdex/payment-streaming/assets/46079535/81a38d2a-e272-41a0-8039-c17262215a3a">

2023-07-13 17:48 UTC, CTAPCKPIM commented
@markholdex 
I corrected what you wrote

2023-07-14 08:13 UTC, almon-s commented
@CTAPCKPIM I believe it should be `expecting` not `expecing` , please fix typo too

2023-07-14 08:50 UTC, CTAPCKPIM commented
@markholdex  / @almon-s 
Fixed
I looked at the difference in the tests on my branch and on the master branch, the difference is 3 tests, namely:
- Claim: only payee can call this function;
- Claim: cliff period is not ended;
- Claim: if reentrant call is detected;

2023-07-14 08:59 UTC, CTAPCKPIM commented
![image](https://github.com/holdex/payment-streaming/assets/83241890/0c77ec0b-f400-4701-8993-8f7add027f73)

Some tests fail, does it make sense to rewrite them? Launching locally in `Hardhat`

2023-07-14 09:24 UTC, zolotokrylin commented
Once the test is written and they are not failing, any introduction to the code which breaks the test must be fixed to make sure the tests are not failing or the tests needs to be rewritten. We should not merge the code which breaks the tests into `main`. The `main` should be pristine

2023-07-14 09:29 UTC, CTAPCKPIM commented
@zolotokrylin 
> Once the test is written and they are not failing, any introduction to the code which breaks the test must be fixed to make sure the tests are not failing or the tests needs to be rewritten. We should not merge the code which breaks the tests into `main`. The `main` should be pristine

Okay, I understand, I will rewrite the tests regarding the changed version of the contract

2023-07-14 09:32 UTC, zolotokrylin commented
Great, Danya

@markholdex @accompany1205 FYI regarding the tests (see the message above)

2023-07-15 12:09 UTC, CTAPCKPIM commented
@zolotokrylin 

If I understand correctly, I did everything, this branch with rewritten tests is ready to be merged, what do you say?

2023-07-17 06:51 UTC, zolotokrylin commented
@CTAPCKPIM github auto test are still failing

2023-07-17 08:14 UTC, markholdex commented
@zolotokrylin autotests will keep failing until we expose our private key inside the code as per @accompany1205 [comment](https://github.com/holdex/payment-streaming/pull/64#issuecomment-1632806307).

2023-07-17 08:51 UTC, almon-s commented
@CTAPCKPIM did you check out Marks comment and the linked comment yet?

> autotests will keep failing until we expose our private key inside the code

2023-07-17 09:27 UTC, CTAPCKPIM commented
@zolotokrylin @markholdex  @almon-s 

I knew what was failing, and tried to solve it 
The task is completed, accept the work)

2023-07-17 10:26 UTC, accompany1205 approved these changes

2023-07-17 10:39 UTC, merged

2023-07-17 10:41 UTC, zolotokrylin commented
@CTAPCKPIM please name the commits and PRs based on the naming convention: https://www.conventionalcommits.org/en/v1.0.0/

2023-07-17 11:01 UTC, CTAPCKPIM commented
@zolotokrylin 
This will need to be done through another PR, as I understand it?

2023-07-17 11:45 UTC, zolotokrylin commented
@CTAPCKPIM what I am saying is when you are naming PRs, please make sure you name it like this:

`test: claim function`
NOT 
`Problem: "claim" function has no test cases`

Please read https://www.conventionalcommits.org/en/v1.0.0/